namespace DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy
{
  public interface IWorkItemServer : DynCon.OSI.VSO.SharedInterfaces.TFS.Client.IITfsTeamProjectCollectionObject ,DynCon.OSI.VSO.SharedInterfaces.TFS.Client.Channels.IITfsRequestListener
  {
    System.String GetWorkitemTrackingVersion( System.String requestId);
    void StampWorkitemCache( System.String requestId);
    void GetWorkItem( System.String requestId, System.Int32 workItemId, System.Int32 revisionId, System.Int32 minimumRevisionId, System.Nullable<System.DateTime> asOfDate, System.Boolean useMaster,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIWorkItemRowSets workItem, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IMetadataTableHaveEntry[] metadataHave,out System.String dbStamp,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIMetadataRowSets metadata);
    void QueryWorkitemRevisions( System.String requestId, System.Xml.XmlElement psQuery, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IQuerySortOrderEntry[] sort, System.Boolean useMaster,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIdRevisionPair[] pairs,out System.DateTime asOfDate, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IMetadataTableHaveEntry[] metadataHave,out System.String dbStamp,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIMetadataRowSets metadata);
    void QueryWorkitems( System.String requestId, System.Xml.XmlElement psQuery, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IQuerySortOrderEntry[] sort, System.Boolean useMaster,out System.Int32[] ids,out System.DateTime asOfDate, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IMetadataTableHaveEntry[] metadataHave,out System.String dbStamp,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIMetadataRowSets metadata);
    void QueryLinkedWorkitems( System.String requestId, System.Xml.XmlElement psQuery, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IQuerySortOrderEntry[] sort, System.Boolean useMaster,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IWorkItemRelation[] relations,out System.DateTime asOfDate, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IMetadataTableHaveEntry[] metadataHave,out System.String dbStamp,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIMetadataRowSets metadata);
    void PageWorkitemsByIds( System.String requestId, System.Int32[] ids, System.String[] columns, System.Int32[] longTextColumns, System.Nullable<System.DateTime> asOfDate, System.Boolean useMaster,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIPagedItemsRowSets items, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IMetadataTableHaveEntry[] metadataHave,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIMetadataRowSets metadata);
    void PageWorkitemsByIdRevs( System.String requestId, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIdRevisionPair[] pairs, System.String[] columns, System.Int32[] longTextColumns, System.Nullable<System.DateTime> asOfDate,out System.DateTime pageDate, System.Boolean useMaster,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIPagedItemsRowSets items);
    void QueryWorkitemCount( System.String requestId, System.Xml.XmlElement psQuery, System.Boolean useMaster,out System.Int32 count,out System.DateTime asOfDate, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IMetadataTableHaveEntry[] metadataHave,out System.String dbStamp,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIMetadataRowSets metadata);
    void GetMetadata( System.String requestId, System.Boolean useMaster, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IMetadataTableHaveEntry[] metadataHave,out System.String dbStamp,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIMetadataRowSets metadata,out System.Int32 locale,out System.Int32 comparisonStyle,out System.String callerIdentity);
    void GetMetadataEx( System.String requestId, System.Boolean useMaster, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IMetadataTableHaveEntry[] metadataHave,out System.String dbStamp,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIMetadataRowSets metadata,out System.Int32 locale,out System.Int32 comparisonStyle,out System.String callerIdentity,out System.String callerIdentitySid);
    void GetMetadataEx2( System.String requestId, System.Boolean useMaster, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IMetadataTableHaveEntry[] metadataHave,out System.String dbStamp,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIMetadataRowSets metadata,out System.Int32 locale,out System.Int32 comparisonStyle,out System.Int32 displayMode);
    System.Boolean BulkUpdate( System.String requestId, System.Xml.XmlElement package,out System.Xml.XmlElement result, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IMetadataTableHaveEntry[] metadataHave,out System.String dbStamp,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIMetadataRowSets metadata);
    void Update( System.String requestId, System.Xml.XmlElement package,out System.Xml.XmlElement result, DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IMetadataTableHaveEntry[] metadataHave,out System.String dbStamp,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IIMetadataRowSets metadata);
    void UpdateMaxAttachmentSize();
    void UploadFile( DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IFileAttachment fileAttachment);
    System.String DownloadFile( System.Int32 fileAttachmentId);
    void GetStoredQuery( System.String requestId, System.Boolean useMaster, System.Guid queryId,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IRowSetCollection queryDataSet);
    void GetStoredQueries( System.String requestId, System.Boolean useMaster, System.Int64 rowVersion, System.Int32 projectId,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IRowSetCollection queriesDataSet);
    void GetStoredQueryItems( System.String requestId, System.Int64 rowVersion, System.Int32 projectId,out DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IRowSetCollection queriesDataSet);
    System.Collections.Generic.IEnumerable<DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IWorkItemId> GetDestroyedWorkItemIds( System.String requestId, System.Int64 rowVersion);
    System.Collections.Generic.IEnumerable<DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IWorkItemId> GetChangedWorkItemIds( System.String requestId, System.Int64 rowVersion);
    System.Collections.Generic.IEnumerable<DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IWorkItemLinkChange> GetWorkItemLinkChanges( System.String requestId, System.Int64 rowVersion);
    DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IExtendedAccessControlListData GetStoredQueryItemAccessControlList( System.String requestId, System.Guid queryItemId, System.Boolean getMetadata);
    void RequestCancel( System.String requestId, System.String cancelRequestId);
    void SyncExternalStructures( System.String requestId, System.String projectURI);
    void SyncBisGroupsAndUsers( System.String requestId, System.String projectUri);
    System.String[] GetReferencingWorkitemUris( System.String requestId, System.String artifactUri);
    DynCon.OSI.VSO.SharedInterfaces.TFS.Client.IIResultCollection<DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Proxy.IArtifactWorkItemIds> GetWorkItemIdsForArtifactUris( System.String[] artifactUris, System.Nullable<System.DateTime> asOfDate);
    void DestroyAttachments( System.String requestId, System.Int32[] workItemIds);
    DynCon.OSI.VSO.SharedInterfaces.TFS.WorkItemTracking.Common.IWorkItemServerVersion WorkItemServerVersion  { get;   }
    System.Int64 MaxAttachmentSize  { get;   }
  }
}
